sum.c

Added a program to find sum cubes of N natural numbers.

Added a program of summation

---

Reverse_Num.c

This returns the reverse of a number

Added Reverse_Number.c

---

Euclid_GCD_algo.py

Added a program in python to compute the Greatest Common Divisor using Euclid's GCD Algorithm

Added a number theory algorithm - Euclid's GCD algorithm

---

RootsOfQuadratic.java

Please Merge
#hacktoberfest 
Pleaseeee

Roots Of Quadratic Equation

---

Calculate surface volume  of a cylinder

Python program to calculate surface volume and area of a cylinder.
Note: A cylinder is one of the most basic curvilinear geometric shapes, the surface formed by the points at a fixed distance from a given straight line, the axis of the cylinder.

Calculate surface volume and area of a cylinder

---

BinarytoDecimal.R
Primenumber.R
sumnaturalnumber.R

Added the R programming language Program.

Added the R Program

---

Calculate Volume and Surface area Of Sphere

Calculate Volume and Surface area Of Sphere

Create Calculate Volume and Surface area Of Sphere

---

index.js

javascript math tips

---

Basic Mathematics Formula

**Basic **Formulas****
Here is a list of **Algebraic formulas** –

Basic Mathematics  Formulas

---

know your birthday
python programme , to know your health status

thank you mayank sir for your outsanding efforts for only us and what do you get in return nothing physically but blessings from almighty and ofcours the likes 
salute sir - excellent effort

Create know your birthday

---

rationalnumbertofraction.py

I created program that convert decimal number to rational number

decimal number to rational number

---

topics explanation with example

this file contains complete math function and operation  related theory with practical example .

Create topics explanation with example

---

star pattern 1.c

here, I added a new star pattern program.

Create star pattern 1.c

---

addition.c

addition is as basic and important.

added addition program

---

Mean_Median_and_Mode.py

Objective
In this challenge, we will calculating the mean, median, and mode using python 3.
Task
Given an array, X , of N integers, calculate and print the respective mean, median, and mode on separate lines. If your array contains more than one modal value, choose the numerically smallest one.
Note: Other than the modal value (which will always be an integer), your answers should be in decimal form, rounded to a scale of  1 decimal place (i.e.,12.3 ,7.0  format).
Input Format
The first line contains an integer, N, denoting the number of elements in the array.
The second line contains  N space-separated integers describing the array's elements.
Output Format
Print  lines of output in the following order:
1) Print the mean on a new line, to a scale of 1  decimal place (i.e.,12.3 , 7.0 ). …

Added Mean_Median_and_Mode.py

---

Triangle_Details.c++

Progam that gives all details of a Triangle given the lengths of its sides

Triangle_Details.cpp

---

Number of Digits in a Factorial.java

This is an Efficient code 
Expected Time Complexity : O(N)
Expected Auxilliary Space : O(1)

Added the Number of Digits in a Factorial Program

---

1_binary_scarch.c

It is an example of Binary search

Binary search

---

matix_multiplication.c

Matrix Multiplication in C language

---

r2codes_Prime_number.c

I added a prime number finder program to your repo.I upload r2codes_Prime.c file in you repo

added prime number finder program

---

frexp()

How frexp() function works in C++

frexp function in c++

---

Polar Coordinates.py

Added Polar coordinates using python

Added Polar coordinates

---

standard deviation.py

Here I have added the Standard Deviation Program in the Mathematics section using Numpy and python language

Added Standard Deviation program

---

Sieve_of_Eratosthenes.py

Python program to print all primes smaller than or equal to N using Sieve of Eratosthenes algorithm. It uses O(nloglog(N)) time complexity using O(N) space complexity where N is the number up to which prime numbers is created, for detail about the algorithm click [here]( https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

Added Sieve_of_Eratosthenes program

---

linked_list.py

Python Program to Create Linked list

Create Linked List
